### ISSUE TITLE
User @bzxys tried to open a 3x position with 0.95 BTC. Instead of reject the transaction due lack of liquidity, a weird position was opened

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-smart-contracts#125] opened 2021-01-26 04:42 UTC
User @bzxys tried to open a 3x position with this transaction:

https://blockscout.com/rsk/mainnet/tx/0x82d6fda2ddd639d4d2d013a569aacfd29b19c15065795f8debd67255c09fd819/token-transfers

There was a lack of sufficient liquidity in lending pool, but instead of reject the openeing of the position, a lend for around 4.700 satoshis was opened.

**Comment by ororopickpocket** [comment] 2021-02-01 14:42
i looked into his position on the contract:

```
{'loanId': 0xb974a64f70f5a1179f8fded6b689ae31daee910f84d025c424784a70034a9838, 'loanToken': '0xef213441A85dF4d7ACbDaE0Cf78004e1E486bB96', 'collateralToken': '0x542fDA317318eBF1d3DEAf76E0b632741A7e677d', 'principal': 1934686296849381404, 'collateral': 950046849390903415, 'interestOwedPerDay': 338652788186700, 'interestDepositRemaining': 1532960448673550, 'startRate': 41093469555435514311290, 'startMargin': 50000000000000000000, 'maintenanceMargin': 15000000000000000000, 'currentMargin': 1660315911669145119161903, 'maxLoanTerm': 2419200, 'endTimestamp': 1612581046, 'maxLiquidatable': 0, 'maxSeizable': 0}
 ```

he's got a loan of 1.9 USD
and collateral of 0.95 BTC
i have no idea how this could happen. this will take some time to investigate.

is he able to close the position on the UI?

**Comment by bzsvy** [comment] 2021-02-01 23:19
Not able / held off closing the position on the UI (see pic). Awaiting directions from devs. Have been working closely with @jjmr007 and last direction provided -->Wait till next UI update (target 2/4) and trading enabled to unwind position ...so I wait.

![image](https://user-images.githubusercontent.com/15135626/106530270-dbcb2280-64a0-11eb-8b31-e90eb660c7d7.png)

**Comment by bzsvy** [comment] 2021-02-01 23:38
Not sure if this could be related to the reason why loan of $1.9 USD occurred. Posting here so that can track down / understand this #issue2 of mine:

wallet: https://explorer.rsk.co/address/0x9642f4781e1e6673b1ad2dec31bc727993bf76ad
* I had transferred ~0.05 BTC a few days before above .95 BTC trade.
* I did a leverage trade with this and made ~$65 USD profit.
* I then performed the .95 3x Margin trade
* For some reason, my wallet balance started showing remaining balance of 0.03 RBC ... not sure what happened to 0.02 BTC?
* Will need that investigated as well ... first want to recover 0.95 BTC vs 0.02 BTC :) 
![image](https://user-images.githubusercontent.com/15135626/106531656-83e1eb00-64a3-11eb-848d-0aa85f2506ca.png)

**Comment by bzsvy** [comment] 2021-02-02 03:30
this should qualify for bug finding bounty no!? ;p

**Comment by bzsvy** [comment] 2021-02-03 03:55
i have now closed my position and recovered .95 btc. thx @jjmr007

**Comment by jjmr007** [comment] 2021-02-05 18:53
This issue has a new incident, with the user CEK#6313 who opened this Short position: 
loanId = 0x1fed14703b3e846ce8c791039e84b323a4fb6334a0f4a7b58f0be65d32e7f2b7
with the intention to be 5x, but the loan was only of 400.000 satoshis (around $150) while his collateral was of $191

Also he opened this long position:
loanId = 0x347280f5c62d5cfffa12984d170709f23a6d53f416c9949cf33ee4adbd5246c7
also with the intention to be 5x, but the loan obtained was of $3,9 while his collateral was of 600.000 satoshis (more than $220)

**Comment by jjmr007** [comment] 2021-02-05 19:36
There is a couple of other users with this same incident: 

I.- User CEK#6313 opened two positions from address 0x15ee3a6e32864d4247ec41f399cb4ead55cf412f

1.-Short position, with loanId: 0x1fed14703b3e846ce8c791039e84b323a4fb6334a0f4a7b58f0be65d32e7f2b7
intended to be 5x, but the loan obtained was 400.000 satoshis (around $154) while the collateral was $190
2.- Long position, with loanId: 0x347280f5c62d5cfffa12984d170709f23a6d53f416c9949cf33ee4adbd5246c7
intended to be 5x, but the loan obtained was of $3,9 while the collateral was 600.000 satoshis (more than $220)

II.- User lactarius#9543 opened one positions from address 0x1996A1c4597721EDAFA2ffe433B0C26B25494ec9

3.- Long position, with loanId: 0x00b46a6052de2b15fdf91b32643393d342ba6903c5d2add5f94f9bc4d0db9556
intended to be 5x, but the loan obtained was of $3,9 while the collateral was 1.000.000 satoshis (around $400)

I think a warning should be publishet to the community

**Comment by ororopickpocket** [comment] 2021-02-07 12:11
@creed-victor and @powerhousefrank are going to look into this.
1. check the params which were sent to the smart contract to find out if the frontend was sending the wrong params (in that case the issue lies on the frontend and i victor's repsonsibility)
2. if the params are correct, the issue is on the smart contract and it's franklin's responsibiliy to look into it (contact me for an explanation of our trading process)

**Comment by creed-victor** [comment] 2021-02-07 17:57
Was able to reproduce it on testnet too when sending BTC/USDT long using BTC as collateral and BPRO/USDT long using BPRO as collateral (the ones with amount in collateralTokenSent instead of loanTokenSent).

For 0.01 BTC with 2x leverage opened position size is 0.01 BTC while it should be 0.002 BTC (tried this will all leverage choices with same outcome).

Checked on params from frontend side and it looks good, so unless contract ABI changed and it's not updated on frontend it shouldn't be issue within frontend.

**Comment by jjmr007** [comment] 2021-02-08 15:05
Update about the Bug: The user CEK#6313 who opened a long 5x position `loanId` : 
0x347280f5c62d5cfffa12984d170709f23a6d53f416c9949cf33ee4adbd5246c7
his vcollateral was of 600.000 satoshis (around $220), but the loan he got was of $3,9 (instead a loan of 4x$220)
This position is opened at a `startRate` of 38,884.292195869885465932 USD/BTC
Today he closed his position at a price close to $44.000... AND HE GOT A LOSS of around 13.500 satoshis (while the cost of the closing transaction is around 5.000 satoshis)

**Comment by ororopickpocket** [comment] 2021-02-08 17:12
please don't mix different user cases in the same issue. it can become confusing. regarding the second user: it's mostly likely an issue due to price misconceptions. we had the oracle rate stored on the loan object, which was shown to the user as start price, although that was not the case. also user were expecting the wrong price when closing a trade. 
the price update is the main improvement of our recent update.  
However, the wrong opening sizes are a huge problem if they are still present.

**Comment by ororopickpocket** [comment] 2021-02-08 17:31
@powerhousefrank i think the problem lies in _totalDeposit

**Comment by powerhousefrank** [comment] 2021-02-19 13:00
This issue was solved.

**Closed by powerhousefrank** 2021-02-19 13:00 UTC
